# Base file is docker-compose.yml
services:
  frontend:
    build:
      target: dev
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/components:/app/components

  question-service:
    environment:
      - BUILD_ENV=dev
    volumes:
      - ./question-service/app:/app/app
  
  user-service:
    build:
      target: dev
    volumes:
      - ./user-service/app:/app/app

  matching-service:
    environment:
      - BUILD_ENV=dev
    volumes:
      - ./matching-service/app:/app/app

  collab-service:
    build:
      target: dev
