services:
  frontend:
    build:
      context: ./frontend
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    depends_on:
      - question-service
      - user-service

  question-service:
    build:
      context: ./question-service
    ports:
      - $QUESTION_SVC_PORT:$QUESTION_SVC_PORT
    environment:
      - PORT=$QUESTION_SVC_PORT
      - DB_URI=$QUESTION_SVC_DB_URI
    depends_on:
      - mongodb-question
  
  user-service:
    build:
      context: ./user-service
    ports:
      - $USER_SVC_PORT:$USER_SVC_PORT
    environment:
      - PORT=$USER_SVC_PORT
      - DB_URI=$USER_SVC_DB_URI
      - JWT_SECRET=$JWT_SECRET
      - EMAIL_ADDRESS=$EMAIL_ADDRESS
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
    depends_on:
      - mongodb-user

  mongodb-question:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_question_data:/data/db

  mongodb-user:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_user_data:/data/db
      - ./init-mongo-scripts/init-mongo-user.sh:/docker-entrypoint-initdb.d/init-mongo-user.sh:ro


  # mongodb-user:
  #   image: mongo:latest
  #   ports:
  #     - 27018:27017
  #   volumes:
  #     - mongodb_user_data:/data/db

volumes:
  mongodb_question_data:
  mongodb_user_data:
