services:
  frontend:
    build:
      context: ./frontend
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    depends_on:
      - question-service
      - user-service

  question-service:
    build:
      context: ./question-service
    ports:
      - $QUESTION_SVC_PORT:$QUESTION_SVC_PORT
    environment:
      - PORT=$QUESTION_SVC_PORT
      - DB_URI=$QUESTION_SVC_DB_URI
  
  user-service:
    build:
      context: ./user-service
    ports:
      - $USER_SVC_PORT:$USER_SVC_PORT
    environment:
      - PORT=$USER_SVC_PORT
      - DB_URI=$USER_SVC_DB_URI
      - JWT_SECRET=$JWT_SECRET
      - EMAIL_ADDRESS=$EMAIL_ADDRESS
      - EMAIL_PASSWORD=$EMAIL_PASSWORD

  matching-service:
    build:
      context: ./matching-service
    ports:
      - $MATCHING_SVC_PORT:$MATCHING_SVC_PORT
    environment:
      - PORT=$MATCHING_SVC_PORT

  api-gateway:
    image: nginx:1.26
    volumes:
      - ./api-gateway/templates:/etc/nginx/templates
    ports:
      - $API_GATEWAY_PORT:$API_GATEWAY_PORT
    environment:
      - PORT=$API_GATEWAY_PORT
      - FRONTEND_PORT=$FRONTEND_PORT
      - USER_SVC_PORT=$USER_SVC_PORT
      - QUESTION_SVC_PORT=$QUESTION_SVC_PORT
      - MATCHING_SVC_PORT=$MATCHING_SVC_PORT
    depends_on:
      - frontend
      - user-service
      - question-service
      - matching-service

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - 6379:6379
