services:
  frontend:
    build:
      context: ./frontend
      args:
        - USER_SVC_PORT=$USER_SVC_PORT
        - QUESTION_SVC_PORT=$QUESTION_SVC_PORT
        - MATCHING_SVC_PORT=$MATCHING_SVC_PORT
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    depends_on:
      - question-service
      - user-service
    environment:
      - PORT=$FRONTEND_PORT

  question-service:
    build:
      context: ./question-service
    ports:
      - $QUESTION_SVC_PORT:$QUESTION_SVC_PORT
    environment:
      - PORT=$QUESTION_SVC_PORT
      - DB_URI=$QUESTION_SVC_DB_URI
      - FRONTEND_PORT=$FRONTEND_PORT
  
  user-service:
    build:
      context: ./user-service
    ports:
      - $USER_SVC_PORT:$USER_SVC_PORT
    environment:
      - PORT=$USER_SVC_PORT
      - DB_URI=$USER_SVC_DB_URI
      - JWT_SECRET=$JWT_SECRET
      - EMAIL_ADDRESS=$EMAIL_ADDRESS
      - EMAIL_PASSWORD=$EMAIL_PASSWORD

  matching-service:
    build:
      context: ./matching-service
    ports:
      - $MATCHING_SVC_PORT:$MATCHING_SVC_PORT
    environment:
      - PORT=$MATCHING_SVC_PORT

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - 6379:6379
