apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: peer-prep
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: jq1836/cs3219-g50-api-gateway:latest
        resources:
          requests:
            memory: "500Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "400m"
      restartPolicy: Always
      imagePullPolicy: Always
