apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  namespace: peer-prep
  labels:
    app: matching-service
spec:
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
      - name: matching-service
        image: jq1836/cs3219-g50-matching-service:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        imagePullPolicy: Always
      restartPolicy: Always
