apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: peer-prep
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: question-service
