name: PR Checks

on:
  pull_request:

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ['style', 'build']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: yarn install
      working-directory: ./frontend
      
    - name: Run ESLint
      if: matrix.check == 'style'
      run: yarn lint
      working-directory: ./frontend

    - name: Run Prettier check
      if: matrix.check == 'style'
      run: yarn prettier --check .
      working-directory: ./frontend
      
    - name: Build
      if: matrix.check == 'build'
      run: yarn build
      working-directory: ./frontend